name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Start services with Docker Compose
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: |
        echo "Waiting for services to be ready..."
        
        # Wait for MCard service
        timeout 120 bash -c 'until curl -f http://localhost:49384/v1/health; do sleep 2; done' || (echo "MCard service failed to start" && exit 1)
        echo "✅ MCard service is ready"
        
        # Wait for PKC app (with healthcheck)
        timeout 120 bash -c 'until curl -f http://localhost:4321; do sleep 2; done' || (echo "PKC app failed to start" && exit 1)
        echo "✅ PKC app is ready"

    - name: Run Playwright tests
      run: npx playwright test PKC_test.spec.js
      env:
        MCARD_BASE_URL: http://localhost:49384/v1
      continue-on-error: false

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 30

    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-videos
        path: test-results/**/*.webm
        retention-days: 7

    - name: Upload test screenshots
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-screenshots
        path: test-results/**/*.png
        retention-days: 7

    - name: Upload error context
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: error-context
        path: test-results/**/*.md
        retention-days: 7

    - name: Stop services
      if: always()
      run: docker-compose down -v